# Generated by Django 5.1.4 on 2025-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="укажите TG chat_id",
                max_length=50,
                null=True,
                verbose_name="TG chat_id",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_nik",
            field=models.CharField(
                blank=True,
                default="default_tg_nik",
                help_text="Укажите TG-ник",
                max_length=50,
                null=True,
                verbose_name="TG",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="добавьте аватарку", null=True, upload_to="avatars/", verbose_name="Аватарка"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="укажите email", max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, help_text="укажите телефон", max_length=15, null=True, verbose_name="Телефон"
            ),
        ),
    ]
